### ISSUE TITLE
Can't install node-opcua on Win7 Pro

### ISSUE THREAD

**Issue by VladBraz125** [node-opcua/node-opcua#617] opened 2019-04-25 13:56 UTC
**I'm submitting a ...**  (check one with "x")

 - (x ) bug report => search github for a similar issue or PR before submitting
 - ( ) feature request
 - (x ) support request => Please do not submit support request here, instead see use 
      - use [gitter](https://gitter.im/node-opcua/node-opcua) or [stackoverflow](https://stackoverflow.com/questions/tagged/node-opcua) for community support, or 
      - [contact Sterfive for commercial support](https://www.sterfive.com)

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

  1. ________________
  2. ________________
  3. ________________
  ...
  
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

  * (x ) my request is related to node-opcua acting as a  OPCUA CLIENT 
  * ( )  my request is related to node-opcua acting as a OPCUA SERVER 

  * ( ) I have installed node-opcua from source ( using git clone)
  * (x ) I have installed node-opcua as a package ( using npm install )
  * ( ) I am using an application that uses node-opcua 
  
       - ( ) node-red
       - ( ) other : please specify 
        
  * Device: __PC___
  * OS version: _____
    
    - (x ) Windows : version : ___7 Pro______
    - ( ) Linux   : version : _________
    - ( ) MacOs   : version : _________
    - ( ) Raspbian: version : _________
    - ( ) Other   : specify :
   
   * Description of the other OPCUA system I am trying to connect to:
   
     - Name:_________
     - Version:_________
     - Manufacturer/Software vendor:_________
     - link : https://
     
    
* **node-opcua version:**  :

* **Node:** 
   `node --version` =

![2019-04-25 15_54_29-New Issue · node-opcua_node-opcua](https://user-images.githubusercontent.com/47737146/56741160-98dc0700-6772-11e9-885c-76bb62dc274a.png)

**Comment by erossignon** [comment] 2019-04-25 21:21
Seems to be with a corrupted package deasync@^0.1.7.
Can anyone else reproduce this as well ?

**Comment by VladBraz125** [comment] 2019-04-26 07:45
The Result of  npm i deasync@^0.1.14 is
npm ERR! code E403
npm ERR! 403 Forbidden: deasync@^0.1.14

**Comment by VladBraz125** [comment] 2019-04-26 08:32
![2019-04-26 10_30_32-Administrator_ C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/47737146/56794471-7ac3e480-680e-11e9-9ea7-13839796cad1.png)

**Comment by erossignon** [comment] 2019-04-26 20:26
What is the nodejs version ? may be it's too old.
Are you on Win32 or 64 ?

**Comment by VladBraz125** [comment] 2019-04-26 20:36
I work with win7 pro 64bit and have a newerste nodejs version. I am until 7.05 in holliday and have no possibility to check somethings.

**Comment by erossignon** [comment] 2019-04-26 21:00
Enjoy your holiday, you do not need to answer straightaway. When you'll be back, let me know the exact answer to your question.. expecially the exact version number of the "newest nodejs version".

**Comment by erossignon** [comment] 2019-05-30 11:47
@VladBraz125  can you please confirm that this issue is now fixed in 0.7.2 and in 2.0.0 as well ?

**Comment by erossignon** [comment] 2019-06-24 12:31
Issue seems to be stalled : closing

**Closed by erossignon** 2019-06-24 12:31 UTC

**Comment by biancode** [comment] 2019-07-11 15:41
deasync needs python-dev to be installed

**Comment by erossignon** [comment] 2019-07-11 15:46
deasync is not used anymore in the most recent versions of  node-opcua aka 0.7.2 and  2.0.0 onwards

**Comment by biancode** [comment] 2019-07-11 19:07
@erossignon hm .. we had that problem today with 0.7.4 and Nodejs 10.16.0

**Comment by erossignon** [comment] 2019-07-11 20:56
interesting ... please try ```npm ls > tree.txt``` and attach the file here
